version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    expose:
      - 5431
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_PASSWORD=superstrongandsecret
      - POSTGRES_USER=restaurant
      - POSTGRES_DB=restaurant
    restart: unless-stopped
  # APP*****************************************
  restaurant:
    image: restaurant:latest
    container_name: restaurant
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5431/restaurant
      - SPRING_DATASOURCE_PASSWORD=superstrongandsecret
      - SPRING_DATASOURCE_USER=restaurant
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres